<a href="https://colab.research.google.com/github/prabhjot1309/Python/blob/main/Prabhjot_kaur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print("hello world")

hello world


*Assignment no. 1*

In [ ]:
#Create variables to store your name (string), age (integer), and course (string). Print all of them
#using a single print() statement.
Name, Age, Course="Prabh",20,"Btech"

print(Name,Age,Course)

Prabh 20 Btech


In [ ]:
#Write a program to swap two numbers without using a third variable. Example: a = 4, b = 9.
x=4
y=9
x,y=y,x
print(x)

9


In [ ]:
#Arithmetic operations
x=20
y=15

print(x+y) #sum
print(x-y )#difference
print(x/y) #divide
print(x%y) #remainder
print(x*y) #product

35
5
1.3333333333333333
5
300


In [ ]:
#Take marks of 5 subjects and calculate the total and percentage
a=80 #subject1
b=97 #subject2
c=78 #subject3
d=89 #subject4
e=85 #subject5

total= a+b+c+d+e
print (total)
percentage= total/500*100
print(percentage)


429
85.8


In [ ]:
#Use compound assignment operators
x = 10
print(x)

x += 5
print(x)

x *= 2
print(x)

x -= 4
print(x)

x /= 2
print(x)


10
15
30
26
13.0


In [ ]:
#Relational operator check
a = 10 # first number
b = 7 #second number

if a == b:
    print("Both are equal")
elif a > b:
    print("First is greater")
else:
    print("Second is greater")


First is greater


In [ ]:
# Logical operator challenge
is_raining = True
have_umbrella = False

print(is_raining & have_umbrella)

print(is_raining | have_umbrella)

if not is_raining or (is_raining and have_umbrella): #not is_raining= false
    print("You can go outside.")                     # is_raining and have_umbrella= false then it gives output false
else:                                                #false or false gives false
    print("You cannot go outside.")

False
True
You cannot go outside.


In [ ]:
#Identity operator
list1 = [1, 2, 3]
list2 = [3, 2, 1]

print(list1 == list2)
print(list1 is list2)

False
False


In [ ]:
#Bitwise operation
a=17
b=23

print(a & b) #AND
print(a|b)  #OR
print(a^b)   #XOR

17
23
6


In [ ]:
# Variable types and typecasting
a = 5
b =4.5

print("Type of int_num:", type(a))
print("Type of float_num:", type(b))

sum  = a+b
print("Sum as integer:",(sum))


Type of int_num: <class 'int'>
Type of float_num: <class 'float'>
Sum as integer: 9.5


*Assignment no. 2*

In [ ]:
#to print number 1 to 10 but stop the loop when number reaches 9
for i in range(1,14):
    if i==9:
        break
    print(i)

1
2
3
4
5
6
7
8


In [ ]:
#to print +ve numbers and show -ve no. when user inputs -ve no
number=int(input("enter the number:"))
if number>= 0:
    print(f"you entered:{number}")
else :
    print("entered no. is negative")

enter the number:6
you entered:6


In [ ]:
#to find first even no. in list using loop and break
list = [2, 3, 6, 5, 7, 8, 12, 34, 57, 89, 75, 67, 45]
for l in list:
    if l % 2 == 0:
        print("First Even number found:", l)
        break


First Even number found: 2


In [ ]:
#keep adding number onwards until total sum exceeds 35 print last sum nd digit
A = [7,5,4,6,2,10,1,9,15,18]
total = 0

for a in A:
    total = total + a
    if total > 25:
        print("Total sum:", total)
        print("Last number added:", a)
        break



Total sum: 34
Last number added: 10


In [ ]:
#keep asking the user to guess the paassword until they guess
#admin123 use while nd break
right_password="admin123"
while True:
    guessed_password= input("Enter the password")
    if guessed_password == right_password:
        print("password is correct.")
        break
    else:
        print("wrong password")




#2nd method
while True:
    guessed_password= input("Enter the password:")
    if guessed_password == "admin123":
        print("password is correct:")
        break
    else:
        print("wrong password")

password is correct.
wrong password


In [ ]:
#give a no. print each digit until a zero is found
number=input("enter the number:")
for digit in number:
    if digit=="0":
        break
    print(digit)

In [ ]:
#to print multiples of 7
for i in range(1, 11):
    print(f"7 x {i} = {7 * i}")


*Assignment no. 3*

In [ ]:
#Take a sentence and reverse the order of its words. Example: "I love Python" → "Python love I"
x= input("Enter a sentence: ")
list1= x.split()
list2 =list1[::-1]
x = ' '.join(list2)

print("Reversed sentence:",x)


Enter a sentence: i love pyhton
Reversed sentence: pyhton love i


In [ ]:
# 2. Given a string of consonants (non-vowels, ignoring case). Example "Hello World" → 7(H,l,l,W,r,l,d).

x=input("Enter a string: ")
vowels='aeiouAEIOU'
consonants=[ i for i in x if i.isalpha() and i not in vowels ]
count=len(consonants)
print(f"{count}({','.join(consonants)})")

Enter a string: hey, myself prabh
11(h,y,m,y,s,l,f,p,r,b,h)


In [ ]:
# 3. Check if two strings are anagrams (same characters, same frequency, ignoring case). Example: "Listen", "Silent" → "Anagram", "Hello" "world" → "Not Anagram".

x=input("Enter first string: ")
y=input("Enter second string: ")

s1=x.replace(" ","").upper()
s2=y.replace(" ","").upper()

if sorted(s1) == sorted(s2):
  print("Anagram")
else:
  print("Not Anagram")


Enter second string: listen
Anagram


In [ ]:
# 4. Find the first character in a string that appears only once (case-sensitive). Example: "Swiss" → "w" "Programming → "r".

x=input("Enter a string: ")

s1=x.replace(" ","").upper()

for i in s1:
  if s1.count(i)==1:
    print(i)
    break
else:
    print("None")


Enter a string: swiss
W


In [ ]:
# 5. Compress a string by replacing repeated characters with the character and count. Example: "aaabbcc" → "a3b2c2", If compressed string isn't shorter return orignal.

x = input("Enter a string: ")

if not x:
    print("")
else:
    compress = ""
    count = 1
    for i in range(1, len(x)):
        if x[i] == x[i - 1]:
            count += 1
        else:
            compress += x[i - 1] + str(count)
            count = 1

    compress += x[-1] + str(count)

    if len(compress) < len(x):
        print("compressed string:", compress)
    else:
        print("no need to compress:", x)


Enter a string: aaabbbbbcccc
compressed string: a3b5c4


In [ ]:
# 6. Find the longest substring in a string thai is a palindrome (case-sensitive). Example: "babad" → "bab" (or"aba"), "cbbd" → "bb".

s=input("Enter a string: ")
x=s.replace(" ","").upper()
n=len(x)

longest=""

for i in range(n):
  for j in range(1,n):
    substr=x[i:j+1]
    if substr == substr[::-1]:
      if len(substr) > len(longest):
        longest = substr
print("Longest palindrome: ",longest)

Enter a string: babad
Longest palindrome:  BAB


In [ ]:
# 7. Gven a string containing only '(',').','{','}','[',']', check if the sequence is valid (properly nested and closed). Example: "[{()}]" → "Valid", "(]" → "Invalid".

x=input("Enter a string: ")
s=[]
dict={')':'(', ']':'[','}':'{' }
valid=True

for i in x:
  if i in '([{':
    s.append(i)
  elif i in ')]}':
    if not s or s[-1] != dict[i]:
      valid= False
      break
    s.pop()

if s:
  valid =False

print("Valid" if valid else "Invalid")

Enter a string: {[[[}})}
Invalid


In [ ]:
# 8. Given a start word, end word, and a list of valid words, find the mininmum number of steps to transform the word to the end word
#by changing one letter at a time, where each intermediate word must be in the list. All words are same length, lowercase.
# Example: start"hot", end="cog", wordlist=["hot","dot","dog",log","lot","cog"] → 5(hit → hot → dot → dog → cog), Return 0 if impossible.

from collections import deque
start = "hit"
end = "cog"
wordList = ["hot", "dot", "dog", "lot", "log", "cog"]
wordSet = set(wordList)
queue= deque([(start, 1)])
while queue:
  word, steps = queue.popleft()
  if word == end:
       print(steps)
       break
  for i in range(len(word)):
       for c in 'abcdefghijklmnopqrstuvwxyz':
           next_word = word[:i] + c + word[i+1:]
           if next_word in wordSet:
               wordSet.remove(next_word)
               queue.append((next_word, steps + 1))
else:
   print(0)

5


*Assignment No. 4*

In [ ]:
#1 Create a dictionary of 5 students with their names as keys and marks as values. Print all the keys and values.
my_dict= {"Rohan":78,"Harman":75,"Aish": 67,"Prabh":84,"Pia":79}
print(my_dict)

{'Rohan': 78, 'Harman': 75, 'Aish': 67, 'Prabh': 84, 'Pia': 79}


In [ ]:
#4 Merge two dictionaries and print the merged dictionary.
dict1= {'a':1,'b':6,'c':10,'d':4}
dict2=  {'e':11,'f':16,'g':5,'h':9}
dict3= dict1|dict2
print(dict3)

{'a': 1, 'b': 6, 'c': 10, 'd': 4, 'e': 11, 'f': 16, 'g': 5, 'h': 9}


In [ ]:
#5 Create a dictionary where the keys are numbers between 1 and 10, and the values are their squares
sq={num:num**2 for num in range(1,11)}
print(sq)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
#6 Write a program that inverts a dictionary (i.e., swaps keys and values). Assume all values are unique.
dict={'a':1,'b':6,'c':10,'d':4,'e':9}
inverted_dict={value: keys for keys, value in dict.items() }
print(inverted_dict)

{1: 'a', 6: 'b', 10: 'c', 4: 'd', 9: 'e'}


In [ ]:
string= "hello world"
freq={}

for char in string:
    if char!= " ":
        freq[char]= freq.get(char,0)+1
print(freq)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


In [ ]:
#7. Given a nested dictionary of students and their subject-wise marks, calculate and print the average marks for each student.
students={ "student1":{'phy':78, 'chem':65,'maths':89,'english': 85},
         "student2":{'phy':79, 'chem':67,'maths':76,'english': 66},
         "student3":{'phy':74, 'chem':55,'maths':84,'english': 98},
         "student4":{'phy':81, 'chem':45,'maths':88,'english': 75},
         "student5":{'phy':38, 'chem':35,'maths':69,'english': 95},
}

for name, subject in students.items():
    avg= sum(subject.values())/len(subject)
    print(name ," average is",avg)



student1  average is 79.25
student2  average is 72.0
student3  average is 77.75
student4  average is 72.25
student5  average is 59.25


In [ ]:
#8. Write a program to group words by their length from a list using a dictionary.
list=['red', 'blue','black','pink','green']
group={}
for word in list:
    l=len(word)
    group.setdefault(l,[]).append(word)


print(group)



{3: ['red'], 4: ['blue', 'pink'], 5: ['black', 'green']}


In [ ]:
#10. Create a program that takes a list of tuples (name, score) and builds a dictionary
#where each name is a key, and the value is a list of all their scores. Then calculate and print
#each person's average score.
list= [('Aditi',78),('Pia',88),('Komal',55),('Prabh',90),('Aditi',74),('Pia',98),('Komal',59),('Prabh',80)]
score_dict={}
for name,score in list:
    if name in  score_dict:
        score_dict[name].append(score)
    else:
        score_dict[name]=[score]
print(score_dict)
for name, score in score_dict.items():
    avg= sum(score)/len(score)
    print(name,"average is",avg)




{'Aditi': [78, 74], 'Pia': [88, 98], 'Komal': [55, 59], 'Prabh': [90, 80]}
Aditi average is 76.0
Pia average is 93.0
Komal average is 57.0
Prabh average is 85.0


*Assignment No. 5*


In [ ]:
#WAP to make a pyramid.
def pyramid(n, current=1):
    if current > n:
        return
    spaces = ' ' * (n - current)
    stars = '*' * (2 * current - 1)
    print(spaces + stars)
    pyramid(n, current + 1)

n=int(input("Enter no. of lines: "))
pyramid(n)

Enter no. of lines: 5
    *
   ***
  *****
 *******
*********


In [ ]:
#Generate a pattern like:
'''
*
* *
* * *
* * * *
'''
def pattern(n, current=1):
    if(current>n):
     return
    print("*"* current)
    pattern(n, current+1)
n= int(input("Enter No.:"))
print(pattern(n))

Enter No.:4
*
**
***
****
None


In [ ]:
#Draw a sqaure pattern like star.
def square_pattern(n):
    for i in range(n):
        print("* " * n)

size = int(input("Enter the size of the square: "))
square_pattern(size)

Enter the size of the square: 6
* * * * * * 
* * * * * * 
* * * * * * 
* * * * * * 
* * * * * * 
* * * * * * 


In [ ]:
#Draw a rectangle pattern like star.
#area of rectangle = lXb
def rectangle_pattern(l,b):
    for i in range(b):
        print("* " * l)
l= int(input("Enter the length of rectangle: "))
b= int(input("Enter the breadth of rectangle: "))
print(rectangle_pattern(l,b))




Enter the length of rectangle: 5
Enter the breadth of rectangle: 2
* * * * * 
* * * * * 
None


*Assignment No. 6*

In [ ]:
#1.  Write a Python program to create a tuple with different data types and print its type.
tuple=('hello', 2, 3.14, True)
print(tuple)
print("type:", type(tuple))

('hello', 2, 3.14, True)
type: <class 'tuple'>


In [ ]:
#2. Given a tuple t = (10, 20, 30, 40, 50), write a program to access the second last element.
t = (10, 20, 30, 40, 50)
second_last= t[-2]
print("second last elemnt is:",second_last)

second last elemnt is: 40


In [ ]:
# 3. Write a program to count the number of times a given element appears in a tuple.
tuple=(2,5,7,8,10,3,5,8,7,12,10,3,8,0)
t= tuple.count(10)
print(t)


2


In [ ]:
#4. Write a program to convert a tuple of strings into a single string. Example: ('Python', 'is', 'fun') --> 'Python is fun'
tuple=('Python', 'is', 'fun')
single_string= ' '.join(tuple)
print (single_string)


Python is fun


In [ ]:
#5. Write a Python program to find the index of an element in a tuple
tuple=(2,5,7,8,10,3,12,0)
t= tuple.index(10)
print(t)

4


In [ ]:
# 6. Write a Python program to create two sets and perform union, intersection, and difference operations.
set1={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
set2={'muskmelon', 'strawberry','kiwi','melon'}

union = set1.union(set2)
print("union:", union)
intersection = set1.intersection(set2)
print("intersection:", intersection)
difference = set1.difference(set2)
print("difference:", difference)

union: {'apple', 'chiku', 'muskmelon', 'mango', 'banana', 'kiwi', 'papaya', 'melon', 'strawberry'}
intersection: {'melon', 'kiwi'}
difference: {'apple', 'chiku', 'mango', 'banana', 'papaya'}


In [ ]:
#7. Write a program to check if a given element is present in a set or not
set ={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
element = input("Enter an element to check: ")

if element in set:
    print(f"{element} is \'present\' in the set.")
else:
    print(f"{element} is \'NOT present\' in the set.")

Enter an element to check: kiwi
kiwi is 'present' in the set.


In [ ]:
#8. Write a program to remove duplicate elements from a list using a set.

list = [10, 20, 10, 30, 40, 20, 60,50,40,20]
unique_list = set(list)

print("Original List:", list)
print("List after removing duplicates:", unique_list)

Original List: [10, 20, 10, 30, 40, 20, 60, 50, 40, 20]
List after removing duplicates: {40, 10, 50, 20, 60, 30}


In [ ]:
#9. Write a Python program to find the symmetric difference between two sets.
set1={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
set2={'muskmelon', 'strawberry','kiwi','melon'}
symmetric_diff = set1.symmetric_difference(set2)
print(symmetric_diff)

{'muskmelon', 'apple', 'chiku', 'mango', 'banana', 'papaya', 'strawberry'}


In [ ]:
#10. Given a list of numbers, write a Python program to find all unique elements using sets.
list=[2,1,5,4,6,3,2,4,8,6,9,2]
unique_elements=set(list)
print("Original List:", list)
print("Unique Elements:", unique_elements)

Original List: [2, 1, 5, 4, 6, 3, 2, 4, 8, 6, 9, 2]
Unique Elements: {1, 2, 3, 4, 5, 6, 8, 9}


*Assignment No. 7*

In [ ]:
#1. Write a function to find the factorial of a number using recursion.
def fact(n):
   if n < 0:
       return "Factorial is not defined for negative numbers"
   elif n == 0 or n == 1:
       return 1
   else:
       result = 1
       for i in range(2, n + 1):
           result *= i
       return result
print(fact(9))

362880


In [ ]:
#2. Write a function that checks whether a number is prime or not.
def is_prime(n):
   if n <= 1:
       return False
   for i in range(2, int(n**0.5) + 1):
       if n % i == 0:
           return False
   return True
print(is_prime(7))

True


In [ ]:
#3. Create a function that takes a string as input and returns the number of vowels in it.
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count
print(count_vowels("Hello! Myself Prabhjot Kaur"))

7


In [ ]:
# 4. Write a function that accepts a list of numbers and returns the maximum and minimum values.
def find_max_min(numbers):
   if not numbers:
       return None
   max_num = min_num = numbers[0]
   for num in numbers:
       if num > max_num:
           max_num = num
       if num < min_num:
           min_num = num
   return max_num, min_num
print(find_max_min([3, 1, 4, 1, 5, 9, 2, 6]))

(9, 1)


In [ ]:
#5. Write a Python function to calculate the nth Fibonacci number using recursion.
def fibonacci(n):
   if n <= 0:
      return []
   elif n == 1:
       return [0]
   elif n == 2:
       return [0, 1]

   fib_series = [0, 1]
   for i in range(2, n):
       next_value = fib_series[i - 1] + fib_series[i - 2]
       fib_series.append(next_value)
   return fib_series
n= int(input("Enter no: "))
print(fibonacci(n))

Enter no: 12
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [ ]:
import math
def find_gcd(a, b):
    return math.gcd(a, b)
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("The GCD is:", find_gcd(num1, num2))

Enter first number: 67
Enter second number: 78
The GCD is: 1


In [ ]:
#7. Write a function that takes a list and returns a new list with only unique elements.
def unique_elements(lst):
    unique_set = set(lst)
    return list(unique_set)

my_list = [1, 2, 2, 3, 4, 4, 5]
print(unique_elements(my_list))


[1, 2, 3, 4, 5]


In [ ]:
#9. Write a function that takes a number and returns True if it is a palindrome, otherwise False.
def is_palindrome(n):
   str_n = str(n)
   return str_n == str_n[::-1]
n=int(input("Enter No.: "))
print(is_palindrome(n))


In [ ]:
# 10. Create a function that takes a temperature in Celsius and returns it in Fahrenheit
#formulaa: c/5=(f-32)/9
def f_to_c(f):
    return 5*(f-32)/9
f=int(input("Enter tempreature:"))
c=f_to_c(f)
print(f"{round(c,3)}, degree celsisus")

#method 2
def celsius_to_fahrenheit(celsius):
   return (celsius * 9/5) + 32
celsisus= int(input("Enter tempreature:"))
print(celsius_to_fahrenheit(celsisus))


Enter tempreature:90
32.222, degree celsisus
Enter tempreature:56
132.8


*Assignment No 9*

In [ ]:
# 1. Create a NumPy array with values from 1 to 10. Print the shape, dimension, and data type of the array.
import numpy as np
arr = np.arange(1, 11)

print("Array:", arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimension: 1
Data type: int64


In [ ]:
#2. Create a 3x3 NumPy array of all zeros and another of all ones. Then create a 3x3 identity matrix.
import numpy as np
zeros_array = np.zeros((3, 3))
print("3x3 Zeros Array:", zeros_array)
ones_array = np.ones((3, 3))
print("\n3x3 Ones Array:", ones_array)
identity_matrix = np.eye(3)
print("\n3x3 Ones identity_matrix:",identity_matrix)

3x3 Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3x3 Ones Array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3x3 Ones identity_matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#3. Generate an array of 15 random integers between 10 and 100 using np.random.randint. Reshape it into a 3x5 matrix and print it.
import numpy as np
arr = np.random.randint(10, 101, size=15)
matrix = arr.reshape(3, 5)
print("3x5 Matrix of random integers between 10 and 100:")
print(matrix)

3x5 Matrix of random integers between 10 and 100:
[[98 96 80 88 55]
 [61 88 60 35 31]
 [96 87 78 57 82]]


In [ ]:
# 4. Create a NumPy array from 1 to 20. Extract every 3rd element starting from index 1 using slicing.
import numpy as np
arr= np.arange(1,21)
print(arr)
print(arr[1:20:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  5  8 11 14 17 20]


In [ ]:
# 5. Create two arrays: a = np.array([2, 4, 6, 8]) and b = np.array([1, 3, 5, 7]). Perform element-wise
#addition, multiplication, and compare which elements in a are greater than in b
import numpy as np
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print(a+b) #addition
print(a*b) #multiplication
print(a>b) #comparison

[ 3  7 11 15]
[ 2 12 30 56]
[ True  True  True  True]


In [ ]:
# 6. Create a NumPy array with 20 random values (0 to 1) using np.random.rand(). Find the mean,
# median, standard deviation, min, and max.
import numpy as np
arr= np.random.rand(20)
print(arr)

print(np.mean(arr))  #mean
print(np.median(arr))  #median
print(np.std(arr))  #standard deviation
print(np.min(arr)) #min
print(np.max(arr))  #max

[0.24106651 0.19215621 0.1956292  0.07360268 0.32706571 0.12172609
 0.64586788 0.06558716 0.47219319 0.8878362  0.06401658 0.57465153
 0.82406715 0.9283193  0.95092756 0.01352873 0.71036762 0.6163373
 0.36671606 0.39533012]
0.4333496385583321
0.3810230880216405
0.3075902549439273
0.013528729183513666
0.9509275598370923


In [ ]:
# 7. Given: arr = np.array([[3, 5], [7, 9]]). Find the sum across rows and columns using axis.
import numpy as np
arr = np.array([[3, 5], [7, 9]])
print(arr)
row_sum= arr.sum(axis=1)
print("sum across rows:",row_sum)
column_sum= arr.sum(axis=0)
print("sum across column:",column_sum)

[[3 5]
 [7 9]]
sum across rows: [ 8 16]
sum across column: [10 14]


In [ ]:
# 8. Create a NumPy array of numbers from 10 to 30. Filter and print only the even numbers using boolean indexing.
import numpy as np
arr = np.arange(10, 31)
even = arr[arr % 2 == 0]
print("Even no.:", even)

Even no.: [10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
# 9. Generate an array of 10 random integers from 1 to 100. Replace all elements greater than 50 with-1.
import numpy as np
arr= np.random.randint(1,101,size=10)
arr[arr>50]=-1
print(arr)

[-1 -1 14 -1 49 -1 31 15 -1 -1]


In [ ]:
#10. Create two arrays: x = np.array([[1, 2], [3, 4]]) and y = np.array([[5, 6], [7, 8]]). Stack them
# vertically and horizontally, then flatten the result into a 1D array.
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((x, y))
h_stack = np.hstack((x, y))
flattened = h_stack.flatten()
print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)
print("Flattened:", flattened)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Flattened: [1 2 5 6 3 4 7 8]


Assignment No 10